# Generated by Django 3.2.11 on 2022-11-16 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('adult', models.BooleanField()),
                ('popularity', models.FloatField()),
                ('poster_path', models.TextField()),
                ('release_date', models.DateField()),
                ('overview', models.TextField(null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('vote_average', models.FloatField()),
                ('original_title', models.CharField(max_length=50)),
                ('original_language', models.CharField(max_length=50)),
                ('vote_count', models.IntegerField(null=True)),
                ('genre_ids', models.ManyToManyField(related_name='genre_movies', to='movies.Genre')),
                ('like_users', models.ManyToManyField(related_name='likeuser_movie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
